# Generated by Django 3.2.4 on 2021-06-24 09:21

from django.db import migrations, models
import renderer.models


class Migration(migrations.Migration):

    dependencies = [
        ('renderer', '0003_alter_score_leader_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='password',
            field=models.CharField(max_length=15, validators=[renderer.models.validate_length]),
        ),
    ]
